console.info("Nama : Ksatria Faikar Nasywaan");
console.info("Tanggal Lahir : 26 April 2007");
console.info("Tempat Lahir : Bandung");
console.info("Agama : Islam");
console.info("Alamat : Katapang");
console.info("Jenis Kelamin : Laki-laki");
console.info("Cita-cita : UI/UX Designer/Pembalap Rally");
console.info("Hobi : Menonton Film, Mendengarkan Musik");
console.info("Orang yang dikagumi : Kiara");
console.info("Quotes : Awali Harimu Dengan Senyum");